/** Site chrome: English (canonical) and hand-reviewed Swahili (no runtime translation API). */
export const ARCHIVE_I18N_KEYS = [
  "heroEyebrow",
  "heroTitleSuffix",
  "heroLead",
  "heroBio",
  "headerDescDesktop",
  "headerDescMobile",
  "navHome",
  "navPoetry",
  "navShortStories",
  "navOnline",
  "navArchive",
  "navFooter",
  "themeToLight",
  "themeToDark",
  "searchPlaceholder",
  "filterAll",
  "filterPoetry",
  "filterShortStories",
  "filterOnline",
  "noResults",
  "actionOpenBook",
  "actionOpenLink",
  "shareBtn",
  "badgePoetry",
  "badgeShortStory",
  "badgeOnline",
  "footerArchive",
  "footerPowered",
  "scrollToArchive",
  "scrollLabel",
  "carouselPrev",
  "carouselNext",
  "carouselGoSlide",
  "alertPreview",
  "alertShareFailed",
  "closeMenu",
  "fabToSwahili",
  "fabToEnglish",
  "heroSlideAlt0",
  "heroSlideAlt1",
  "heroSlideAlt2",
  "uhakikiReview",
] as const;

export type ArchiveI18nKey = (typeof ARCHIVE_I18N_KEYS)[number];

export const ARCHIVE_EN: Record<ArchiveI18nKey, string> = {
  heroEyebrow: "Digital archive · Author & public voice",
  heroTitleSuffix: "Publications Archive",
  heroLead:
    "Explore poetry, short stories, and online resources — videos, reviews, and articles open in a new tab.",
  heroBio:
    "Ally Saleh is a prominent Zanzibari politician, lawyer, journalist, and poet, known for a long career in both the media and political landscapes of Zanzibar. He served as Member of Parliament for the Malindi constituency. Originally a high-profile member of the Civic United Front (CUF), he later joined ACT Wazalendo. He is a vocal advocate for Zanzibari autonomy and has spoken widely on Zanzibar identity and the nature of the Tanzanian Union.",
  headerDescDesktop: "Publications archive · Poetry, short stories & online",
  headerDescMobile: "Publications archive",
  navHome: "Home",
  navPoetry: "Poetry",
  navShortStories: "Short stories",
  navOnline: "Online",
  navArchive: "Archive",
  navFooter: "Footer",
  themeToLight: "Switch to light mode",
  themeToDark: "Switch to dark mode",
  searchPlaceholder: "🔍 Search titles & descriptions…",
  filterAll: "All",
  filterPoetry: "Poetry",
  filterShortStories: "Short stories",
  filterOnline: "Online",
  noResults: "No matching publications — try other keywords",
  actionOpenBook: "Open book",
  actionOpenLink: "Open link",
  shareBtn: "Share",
  badgePoetry: "Diwani",
  badgeShortStory: "Hadithi",
  badgeOnline: "External link",
  footerArchive: "Ally Saleh — Digital Archive · Documents by the author",
  footerPowered: "Proudly powered by",
  scrollToArchive: "Scroll to archive",
  scrollLabel: "Scroll",
  carouselPrev: "Previous slide",
  carouselNext: "Next slide",
  carouselGoSlide: "Go to slide",
  alertPreview:
    '✨ "%s" — preview mode. Full content available in archive.',
  alertShareFailed:
    "Sharing failed. Open the work’s button and copy the URL from the browser.",
  closeMenu: "Close navigation menu",
  fabToSwahili: "Translate page to Swahili",
  fabToEnglish: "Show page in English",
  heroSlideAlt0: "Ally Saleh portrait",
  heroSlideAlt1: "Ally Saleh archive photo",
  heroSlideAlt2: "Ally Saleh publication archive",
  uhakikiReview: "Review",
};

/** Swahili UI matching the provided full-page copy (static, instant toggle). */
export const ARCHIVE_SW: Record<ArchiveI18nKey, string> = {
  heroEyebrow: "Hifadhi ya kidijitali · Mwandishi na sauti ya umma",
  heroTitleSuffix: "Hifadhi ya Machapisho",
  heroLead:
    "Chunguza mashairi, hadithi fupi na nyenzo za mtandaoni — video, tathmini na makala zimefunguliwa kwenye kichupo kipya.",
  heroBio:
    "Ally Saleh ni mwanasiasa maarufu wa Kizanzibari, mwanasheria, mwandishi wa habari, na mshairi, anayejulikana kwa kazi ndefu katika vyombo vya habari na mandhari ya kisiasa ya Zanzibar. Alihudumu kama Mbunge wa jimbo la Malindi. Awali alikuwa mwanachama wa ngazi ya juu wa Civic United Front (CUF), baadaye alijiunga na ACT Wazalendo. Yeye ni mtetezi wa uhuru wa Wazanzibari na amezungumza sana juu ya utambulisho wa Zanzibar na asili ya Umoja wa Tanzania.",
  headerDescDesktop:
    "Hifadhi ya machapisho · Mashairi, hadithi fupi na mtandaoni",
  headerDescMobile: "Hifadhi ya machapisho",
  navHome: "Mwanzo",
  navPoetry: "Ushairi",
  navShortStories: "hadithi fupi",
  navOnline: "Mtandaoni",
  navArchive: "Kumbukumbu",
  navFooter: "Wayotini",
  themeToLight: "Badilisha mwonekano mwanga",
  themeToDark: "Badilisha mwonekano giza",
  searchPlaceholder: "🔍 Tafuta vichwa na maelezo…",
  filterAll: "Vyote",
  filterPoetry: "Ushairi",
  filterShortStories: "hadithi fupi",
  filterOnline: "Mtandaoni",
  noResults: "Hakuna machapisho yanayofanana — jaribu maneno mengine",
  actionOpenBook: "Fungua kitabu",
  actionOpenLink: "Fungua kiunganishi",
  shareBtn: "Shiriki",
  badgePoetry: "Diwani",
  badgeShortStory: "Hadithi",
  badgeOnline: "Kiunganishi cha nje",
  footerArchive: "Ally Saleh — Hifadhi ya Kidijitali · Hati na mwandishi",
  footerPowered: "Inaendeshwa kwa kiburi na",
  scrollToArchive: "Teleza hadi kumbukumbu",
  scrollLabel: "Teleza",
  carouselPrev: "Kidelelesha kilichotangulia",
  carouselNext: "Kidelelesha kinachofuata",
  carouselGoSlide: "Nenda kwa kidelelesha",
  alertPreview:
    '✨ "%s" — hali ya hakiki. Yaliyomo kamili yapo katika kumbukumbu.',
  alertShareFailed:
    "Kushiriki kumeshindikana. Fungua kitufe cha kazi na unakisi URL kutoka kwenye kivinjari.",
  closeMenu: "Funga menyu ya urambazaji",
  fabToSwahili: "Badili ukurasa kwa Kiswahili",
  fabToEnglish: "Onyesha ukurasa kwa Kiingereza",
  heroSlideAlt0: "Picha ya Ally Saleh",
  heroSlideAlt1: "Picha ya Ally Saleh katika kumbukumbu",
  heroSlideAlt2: "Machapisho ya Ally Saleh",
  uhakikiReview: "review",
};
